apiVersion: v1
kind: Service
metadata:
  name: {{ include "kilnAPI.fullname" . }}-client-svc
  labels:
    {{- include "kilnAPI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kilnAPI.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.kilnAPI.service.port }}
      protocol: TCP
  selector:
    {{- include "kilnAPI.selectorLabels" . | nindent 4 }}
